# Before using, change permissions to make executable with chmod

# Define the shell
#PBS -S /bin/bash

# Name the job
#PBS -N add_eof_test

# Request resources
#PBS -l walltime=00:30:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb

# Specify the standard output file (rather than printing to screen)
#PBS -o /home/mleukam/logs/addeof.output.log

# Specify the standard error (rather than printing to screen)
#PBS -e /home/mleukam/logs/addeof.error.log

# Load compilers and modules
module load gcc/6.2.0
module load python/3.6.0

# navigate to shell dir
cd /home/mleukam/shell

# call python scrpt
./bam_add_eof.py

# exit code
exit 0
