## Before using, change permissions to make executable with chmod

## Define the shell
#PBS -S /bin/bash

## Name the job
#PBS -N make_sam_test

## Request resources
#PBS -l walltime=00:30:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=16gb

## Specify the standard output file (rather than printing to screen)
#PBS -o /home/mleukam/logs/makesamtest.output.log

## Specify the standard error (rather than printing to screen)
#PBS -e /home/mleukam/logs/makesamtest.error.log

# navigate to shell dir
cd /home/mleukam/shell

# call shell scrpt
./makesamtest.sh

# exit code
exit 0
